const mail = "sersicoh@gmail.com";
export const content = {
  person: {
    name: "Wojciech Szymczak",
    photo_link: "https://avatars.githubusercontent.com/u/106604791?v=4",
    photo_alt: "My personal phot",
    description:
      "I am fascinated by React in TypeScript and I am currently developing this passion by working with these technologies on a daily basis. I would like to spread my wings and since you are already on this website, check what I can do and write to me",
    mail: mail,
  },
  skillsTypes: [
    {
      title: "My skillset includes 🛠️",
      skills: [
        "React",
        "TypeScript",
        "JavaScript ES6+",
        "Adobe Photoshop Scripts (ES3)",
        "Next.js",
        "REST API",
        "Redux",
        "GitHub/Lab",
        "CSS",
        "Tailwind",
        "Styled-components",
        "STRAPI",
        "React Hooks",
        "React Testing Library",
        "Promises, Async/Await",
        "NPM",
        "Markdown",
        "Scrum",
        "Jira",
        "Confluence",
        "BPMN 2.0",
        "Writing docs",
        "Teamwork",
      ],
    },
    {
      title: "What I want to learn next 🚀",
      skills: [
        "TypeScript improoving",
        "Next.js improoving",
        "Node.js",
        "webpack",
        "React Native",
        "AWS S3",
        "Kotlin",
        "Android SDK",
        "WordPress",
        "CI/CD pipelines",
      ],
    },
  ],
  footer: {
    mail: mail,
    description: `If you're already at the end of the page, you probably liked it. Check out how this page was written here: `,
    repo_text: "repo link",
    repo_link: "https://github.com/sersicoh/personal-home-page",
    github_link: "https://github.com/sersicoh",
    facebook_link: "https://www.facebook.com/sersicoh",
    linkedIn_link: "https://www.linkedin.com/in/wojtek-szymczak-6a53b423a/",
  },
};
