export const colors = {
  white: "#ffffff",
  whiteLilac: "#FBFBFE",
  mercury: "#E5E5E5FF",
  iron: "#D1D5DA",
  anakiwa: "#8CC2FF",
  shipCove: "#6D93BEFF",
  dodgerBlue: "#2188FFFF",
  scienceBlue: "#0366D6",
  azureRadiance: "#0366D680",
  blueBayoux: "#0366D633",
  slateGray: "#6E7E91",
  manatee: "#D1D5DA4C",
  mineShaft: "#252525",
  celtic: "#14462033",
  mineShaftLight: "#363636",
  violet: "#090A330A",
};

export const theme = {
  breakpoint: {
    mobileMax: 767,
    tabletMax: 960,
    maxContentSize: 1216,
  },
  lightMode: {
    colors: {
      background: colors.whiteLilac,
      backgroundContainer: colors.whiteLilac,
      h1: colors.mineShaft,
      h2: colors.mineShaft,
      h3: colors.mineShaft,
      underLine: colors.mercury,
      paragraphMid: colors.mineShaft,
      paragraphLead: colors.slateGray,
      mail: colors.mineShaft,
      mailHover: colors.scienceBlue,
      dot: colors.scienceBlue,
      link: colors.scienceBlue,
      linkUnderLine: colors.blueBayoux,
      crumb: colors.slateGray,
      buttonText: colors.white,
      backgroundButton: colors.scienceBlue,
      buttonBorder: colors.iron,
      buttonFocus: colors.anakiwa,
      buttonSelected: colors.celtic,
      icon: colors.mineShaft,
      iconBlue: colors.scienceBlue,
      iconHover: colors.scienceBlue,
      loadingIconPositive: colors.manatee,
      loadingIconNegative: colors.scienceBlue,
      errorIcon: colors.mineShaft,
      shadow: colors.violet,
      border: colors.manatee,
      projectTileTitle: colors.scienceBlue,
      projectTileOnHover: colors.blueBayoux,
    },
  },
  darkMode: {
    colors: {
      background: colors.mineShaft,
      backgroundContainer: colors.mineShaftLight,
      h1: colors.white,
      h2: colors.white,
      h3: colors.white,
      underLine: colors.mercury,
      paragraphMid: colors.white,
      paragraphLead: colors.white,
      mail: colors.white,
      mailHover: colors.dodgerBlue,
      dot: colors.dodgerBlue,
      link: colors.dodgerBlue,
      linkUnderLine: colors.scienceBlue,
      crumb: colors.white,
      buttonText: colors.white,
      backgroundButton: colors.dodgerBlue,
      buttonBorder: colors.shipCove,
      buttonFocus: colors.anakiwa,
      buttonSelected: colors.celtic,
      icon: colors.white,
      iconBlue: colors.dodgerBlue,
      iconHover: colors.dodgerBlue,
      loadingIconPositive: colors.mineShaftLight,
      loadingIconNegative: colors.dodgerBlue,
      errorIcon: colors.white,
      shadow: colors.violet,
      border: colors.manatee,
      projectTileTitle: colors.white,
      projectTileOnHover: colors.azureRadiance,
    },
  },
};
